BATCH_SIZE = 128
SEQUENCE_LENGTH = 2

DISTANCE_RATE = 5

FRAME = 0.02
SPEED = 5 // DISTANCE_RATE
DRAGON_WIDTH = 30 // DISTANCE_RATE
DRAGON_HEIGHT = 50 // DISTANCE_RATE
JUMP_V = -300 // DISTANCE_RATE
FLOOR_Y = 800 // DISTANCE_RATE
G = 9.8 * 30 // DISTANCE_RATE  # g
SIZE = [1500 // DISTANCE_RATE, 1000 // DISTANCE_RATE]
CACTUS_Y = 730 // DISTANCE_RATE
DEAD_BOTTOM = 900 // DISTANCE_RATE
CACTUS_WIDTH = 40 // DISTANCE_RATE
CACTUS_HEIGHT = 100 // DISTANCE_RATE

RAVEN_BOTTOM = 800 // DISTANCE_RATE
RAVEN_WIDTH = 100 // DISTANCE_RATE
RAVEN_HEIGHT = 20 // DISTANCE_RATE
RAVEN_Y_BLANK = 50 // DISTANCE_RATE

DRAGON_X_INIT = 200 // DISTANCE_RATE
DRAGON_Y_INIT = 760 // DISTANCE_RATE

LEFT_BOUND = -200 // DISTANCE_RATE
RANDOM_X = 2200 / DISTANCE_RATE

STATE_STEPS = 4
